export enum UserCan {

  USER = "USER",
  MODERATOR = "MODERATOR",
  ADMIN = "ADMIN",

  VIEW_PARENT = "VIEW_PARENT",
  VIEW_CHILD = "VIEW_CHILD",
  VIEW_MENU = "VIEW_MENU",
  VIEW_RECENT_EVENT_LIST = "VIEW_RECENT_EVENT_LIST",
  VIEW_EVENT_LIST = "VIEW_EVENT_LIST",
  VIEW_EDIT_MODERATOR = "VIEW_EDIT_MODERATOR",
  VIEW_CREATE_MODERATOR = "VIEW_CREATE_MODERATOR"
}
